export const ROUTE_NAMES = {
    HOME: 'home',
    DASHBOARD: 'dashboard',
    SUPPLIERS: 'suppliers',
    PRODUCTS: 'products',
    ORDERS: 'orders',
    EMPLOYEES: 'employees',
    CUSTOMERS: 'customers',
    CUSTOMER_PROFILE: 'customer',
    SEARCH: 'search',
    SUPPLIER_PROFILE: 'supplier',
    PRODUCT_PROFILE: 'product',
    ORDER_PROFILE: 'order',
    EMPLOYEE_PROFILE: 'employee',
};
